name: LamaCore
version: 1.0
author: Mylogo
main: LamaCore

commands:
  home:
    description: Teleports to your home
    aliases: [h]
  sethome:
    description: Sets your home
    aliases: [homeset, sh, hs]
  delhome:
    aliases: [homedel, dh, hd]
  homes:
    aliases: [listhome, homelist, hl, lh]
  invsee:
    aliases: [is]
  tpa:
    aliases: [tpr]
  tpaccept:
    aliases: [ta]
  tpdeny:
    aliases: [td]
  spawn:
    aliases: [s]
  setspawn:
    description: Sets spawn
  vanish:
    aliases: [v]
  fly:
    aliases: [f]
  kit:
    aliases: [kits]
  enderchest:
    aliases: [echest]
  clan:
    aliases: [clans, c]
  admhome:
  admhometp:
  shop:
  hat:
  efly:
  gm: